/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void bc1(GButton source, GEvent event) { //_CODE_:button1:843294:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  txaEvents.appendText("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  algorA();
  write(false);
} //_CODE_:button1:843294:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:txaEvents:357466:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
  txaEvents.appendText("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:txaEvents:357466:

public void bc2(GButton source, GEvent event) { //_CODE_:button2:260861:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  txaEvents.appendText("button2 - GButton >> GEvent." + event + " @ " + millis());
  
  algorB();
  write(false);
} //_CODE_:button2:260861:

public void bc_palo(GButton source, GEvent event) { //_CODE_:button2:260861:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  txaEvents.appendText("button2 - GButton >> GEvent." + event + " @ " + millis());
  
  solve_palo();
  write(false);
} //_CODE_:button2:260861:

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 21, 33, 80, 30);
  button1.setText("Algoritmus_A");
  button1.setTextBold();
  button1.addEventHandler(this, "bc1");
  txaEvents = new GTextArea(this, 180, 23, 331, 117, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  txaEvents.setOpaque(true);
  txaEvents.addEventHandler(this, "textarea1_change1");
  button2 = new GButton(this, 21, 71, 80, 30);
  button2.setText("Algoritmus_B");
  button2.setTextBold();
  button2.addEventHandler(this, "bc2");
  
  //palo button
  button_palo = new GButton(this, 21, 108, 80, 30);
  button_palo.setText("Algoritmus_palo");
  button_palo.setTextBold();
  button_palo.addEventHandler(this, "bc_palo");
  
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextArea txaEvents; 
GButton button2; 
GButton button_palo;